version: 2

sources:
  - name: raw_data
    database: supplychain360_db
    schema: raw
    tables:
      - name: suppliers
      - name: warehouses
      - name: store_locations
      - name: products
      - name: inventories
      - name: sales
      - name: shipments