{{ config(
    materialized='table',
    schema='silver'
) }}

with inventories as (
    select * from {{ ref('int_inventories_cleaned') }}
),

products as (
    select * from {{ ref('int_products_cleaned') }}
),

warehouses as (
    select * from {{ ref('int_warehouses_cleaned') }}
),

enriched as (
    select
        -- Composite Key (Grain: Product per Warehouse per Day) Generated by a custom macro
        {{ generate_surrogate_key(['i.product_id', 'i.warehouse_id', 'i.snapshot_date']) }} as inventory_status_id,
        
        -- Foreign Keys
        i.product_id,
        i.warehouse_id,
        p.supplier_id,
        
        -- Dimensions for Filtering
        p.product_name,
        p.category as product_category,
        p.brand as product_brand,
        w.city_name as warehouse_city,
        w.state_code as warehouse_state,
        
        -- Metrics
        i.quantity_available,
        i.reorder_threshold,
        
        -- Stock Health Calculations
        case 
            when i.quantity_available = 0 then 'OUT_OF_STOCK'
            when i.quantity_available <= i.reorder_threshold then 'LOW_STOCK'
            else 'HEALTHY'
        end as stock_status,
        
        -- Stock Coverage Ratio (How many multiples of the threshold do we have?)
        case 
            when i.reorder_threshold > 0 
            then cast(i.quantity_available as decimal) / i.reorder_threshold 
            else null 
        end as stock_coverage_ratio,
        
        -- Timestamps
        i.snapshot_date,
        i.bronze_ingested_at as processed_at

    from inventories i
    inner join products p on i.product_id = p.product_id
    inner join warehouses w on i.warehouse_id = w.warehouse_id
)

select * from enriched